In [1]:
import sklearn 

In [2]:
#Virtual Env

from sklearn.linear_model import LinearRegression
import numpy as np

In [3]:
X = [1,3,4,6]
y = [1,2,5,6]

In [5]:
X = np.array(X)
y = np.array(y)

In [11]:
X = X.reshape(-1, 1)
y = y.reshape(-1, 1)

In [6]:
model = LinearRegression()

In [10]:
model.fit(X,y)

LinearRegression()

In [12]:
y_pred = model.predict(X)

In [13]:
y_pred

array([[0.80769231],
       [2.96153846],
       [4.03846154],
       [6.19230769]])

In [14]:
y

array([[1],
       [2],
       [5],
       [6]])

In [15]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error, r2_score

In [16]:
mean_squared_error (y, y_pred)

0.4807692307692307

In [17]:
mean_absolute_error(y, y_pred)

0.5769230769230766

In [19]:
r2_score(y,y_pred)

0.8868778280542986

In [20]:
model.coef_

array([[1.07692308]])

In [21]:
model.intercept_

array([-0.26923077])