In [44]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [45]:
print(type(a))

<class 'numpy.ndarray'>


In [46]:
print(a.shape)

(3,)


In [47]:
print(a[1])

2


In [48]:
a[0] = 3

In [49]:
print (a)

[3 2 3]


In [50]:
a2d = np.array([[1,2,3],[4,5,6]])

In [51]:
print(a2d)
print(a2d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [52]:
print(type(a2d))

<class 'numpy.ndarray'>


In [53]:
a2d.dtype

dtype('int64')

In [54]:
a2d[0,2]

3

In [55]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],np.float32)

b = a.reshape(4,4)

In [56]:
print(b)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [57]:
b.dtype

dtype('float32')

In [58]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [59]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [60]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
ide = np.diag([1,2,3,4,5])

In [64]:
b

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]], dtype=float32)

In [65]:
b[1:,1:]

array([[ 6.,  7.,  8.],
       [10., 11., 12.],
       [14., 15., 16.]], dtype=float32)

In [66]:
b[:1,:]

array([[1., 2., 3., 4.]], dtype=float32)

In [67]:
print(list(range(1,10,2)))

[1, 3, 5, 7, 9]


In [68]:
b[::2,::3]

array([[ 1.,  4.],
       [ 9., 12.]], dtype=float32)

In [69]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],np.float32)

arr1 = arr1.reshape(4,4)

print(arr1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [70]:
arr2 = np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160],np.float32)

arr2 = arr2.reshape(4,4)

print(arr2)

[[ 10.  20.  30.  40.]
 [ 50.  60.  70.  80.]
 [ 90. 100. 110. 120.]
 [130. 140. 150. 160.]]


In [86]:
arr1

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]], dtype=float32)

In [87]:
arr2

array([[ 10.,  20.,  30.,  40.],
       [ 50.,  60.,  70.,  80.],
       [ 90., 100., 110., 120.],
       [130., 140., 150., 160.]], dtype=float32)

In [88]:
print(arr1-arr2)

[[  -9.  -18.  -27.  -36.]
 [ -45.  -54.  -63.  -72.]
 [ -81.  -90.  -99. -108.]
 [-117. -126. -135. -144.]]


In [89]:
print(np.add(arr1,arr2))

[[ 11.  22.  33.  44.]
 [ 55.  66.  77.  88.]
 [ 99. 110. 121. 132.]
 [143. 154. 165. 176.]]


In [90]:
print(np.subtract(arr1,arr2))

[[  -9.  -18.  -27.  -36.]
 [ -45.  -54.  -63.  -72.]
 [ -81.  -90.  -99. -108.]
 [-117. -126. -135. -144.]]


In [91]:
print(np.multiply(arr1,arr2))

[[  10.   40.   90.  160.]
 [ 250.  360.  490.  640.]
 [ 810. 1000. 1210. 1440.]
 [1690. 1960. 2250. 2560.]]


In [92]:
print(np.divide(arr1,arr2))

[[0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]]


In [94]:
arr1.dot(arr2)

array([[ 900., 1000., 1100., 1200.],
       [2020., 2280., 2540., 2800.],
       [3140., 3560., 3980., 4400.],
       [4260., 4840., 5420., 6000.]], dtype=float32)

In [77]:
#Broadcasting in numpy


a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10],[40]])
print(a)
print(b)


[[1 2 3]
 [4 5 6]]
[[10]
 [40]]


In [78]:
np.add(a,b)

#[[10,10,10],[40,40,40]]

array([[11, 12, 13],
       [44, 45, 46]])

In [95]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
np.sum(a)

21

In [80]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
np.mean(a,axis=1)

array([2., 5.])

In [98]:
np.mean(a,axis=0)

array([2.5, 3.5, 4.5])

In [99]:
np.std(a,axis = 0)

array([1.5, 1.5, 1.5])

In [100]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [101]:
np.random.rand(5,5)

#print(np.random.rand.__doc__)

array([[0.23076711, 0.4925609 , 0.34042241, 0.32011987, 0.90740626],
       [0.35249139, 0.95550354, 0.8129988 , 0.72691695, 0.31635711],
       [0.3550516 , 0.76624189, 0.82923301, 0.38420155, 0.40067465],
       [0.3988053 , 0.72595172, 0.76266223, 0.42408792, 0.17760874],
       [0.019513  , 0.3203399 , 0.71930731, 0.33161841, 0.09565101]])