In [1]:
import numpy as np

In [10]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(4,)

In [6]:
len(a)

4

In [ ]:
# Properties of Matrix

a = (3, 3)
b = (3, 2)

a = (3, 3)
b = (3, 4)

a = (3, 3)
b = (1, 2)

- do

In [11]:
b = a.reshape((3,3))

In [12]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
b[0, 0]

1

In [17]:
b[-3,0]

1

In [18]:
b[0,-3]

1

In [19]:
b[-3,-3]

1

In [15]:
b[2, 1]

8

In [ ]:
b[3, -1]

In [20]:
b[0:2, 1]

array([2, 5])

In [21]:
b[1, 1:]

array([5, 6])

In [22]:
b[1:, 1:]

array([[5, 6],
       [8, 9]])

In [23]:
b[0:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [24]:
b[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [28]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
b[:, ::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [27]:
b[1:, ::2]

array([[4, 6],
       [7, 9]])

In [29]:
b[::2, ::2]

array([[1, 3],
       [7, 9]])

In [30]:
from numpy import array, argmin, sqrt, sum


In [31]:
observation = array([111.0, 188.0])
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])
diff = codes - observation 

In [32]:
diff

array([[ -9.,  15.],
       [ 21.,   5.],
       [-66., -33.],
       [-54., -15.]])

In [ ]:
#scalar

magnitude - values (100)

In [ ]:
#vector
#magnitude with direction


In [ ]:
#tensor - Vectors of Vectors

In [33]:
import numpy as np
import time 
import sys

# Creating a NumPy array with 100 elements
array = np.arange(100)
# array.itemsize : Size of one element
# array.size : length of array
print("Size of NumPy array: ", array.size * array.itemsize)

# Creating a list with 100 elements
# Now I'll print the size of list
list = range(0, 100)
# Multiplying size of 1 element with length of the list
print("Size of list: ", sys.getsizeof(1)*len(list))

Size of NumPy array:  800
Size of list:  2800


In [36]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
list

range(0, 100)

In [38]:
import numpy as np
import time
import sys

# let's declare the size
Size = 100000

# Creating two lists
list1 = range(Size)
list2 = range(Size)

# Creating two NumPy arrays
arr1 = np.arange(Size)
arr2 = np.arange(Size)

# Calculating time for Python list
start = time.time()
result = [(x+y) for x, y in zip(list1, list2)]
          
print("Time for Python List in msec: ", (time.time() - start) * 1000)

# Calculating time for NumPy array
start = time.time()
result = arr1+arr2
print("Time for NumPy array in msec: ", (time.time()- start) * 1000)

print("This means NumPy array is faster than Python List")

Time for Python List in msec:  12.957572937011719
Time for NumPy array in msec:  0.45013427734375
This means NumPy array is faster than Python List


In [40]:
import numpy as np
import time

a1 = np.array([1, 2, 3])
a2 = np.array([0, 5, 6])

# To add two array you can simply do it by
print("ADD a1 and a2 elements : ", a1+a2)

# To sub two array you can simply do it by
print("SUB a1 and a2 elements : ", a1 - a2)

# To mul two array you can simply do it by
print("MUL a1 and a2 elements : ", a1 / a2)

# Calculating time for NumPy array
start = time.time()
result = arr1+arr2
print("Time for NumPy array in msec: ", (time.time()- start) * 1000)

ADD a1 and a2 elements :  [1 7 9]
SUB a1 and a2 elements :  [ 1 -3 -3]
MUL a1 and a2 elements :  [inf 0.4 0.5]
Time for NumPy array in msec:  0.4811286926269531


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in true_divide
  


In [41]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))


In [42]:
a

array([[[[  0,   1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10,  11],
         [ 12,  13,  14,  15,  16,  17],
         [ 18,  19,  20,  21,  22,  23],
         [ 24,  25,  26,  27,  28,  29]],

        [[ 30,  31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40,  41],
         [ 42,  43,  44,  45,  46,  47],
         [ 48,  49,  50,  51,  52,  53],
         [ 54,  55,  56,  57,  58,  59]],

        [[ 60,  61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70,  71],
         [ 72,  73,  74,  75,  76,  77],
         [ 78,  79,  80,  81,  82,  83],
         [ 84,  85,  86,  87,  88,  89]],

        [[ 90,  91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100, 101],
         [102, 103, 104, 105, 106, 107],
         [108, 109, 110, 111, 112, 113],
         [114, 115, 116, 117, 118, 119]]],


       [[[120, 121, 122, 123, 124, 125],
         [126, 127, 128, 129, 130, 131],
         [132, 133, 134, 135, 136, 137],
         [138, 139, 140, 141, 142, 143],
      

In [43]:
b

array([[[[359, 358, 357],
         [356, 355, 354],
         [353, 352, 351],
         [350, 349, 348],
         [347, 346, 345],
         [344, 343, 342]],

        [[341, 340, 339],
         [338, 337, 336],
         [335, 334, 333],
         [332, 331, 330],
         [329, 328, 327],
         [326, 325, 324]],

        [[323, 322, 321],
         [320, 319, 318],
         [317, 316, 315],
         [314, 313, 312],
         [311, 310, 309],
         [308, 307, 306]],

        [[305, 304, 303],
         [302, 301, 300],
         [299, 298, 297],
         [296, 295, 294],
         [293, 292, 291],
         [290, 289, 288]]],


       [[[287, 286, 285],
         [284, 283, 282],
         [281, 280, 279],
         [278, 277, 276],
         [275, 274, 273],
         [272, 271, 270]],

        [[269, 268, 267],
         [266, 265, 264],
         [263, 262, 261],
         [260, 259, 258],
         [257, 256, 255],
         [254, 253, 252]],

        [[251, 250, 249],
         [248, 247, 246]

In [44]:
np.dot(a, b)[2,3,2,1,2,2]
499128
sum(a[2,3,2,:] * b[1,2,:,2])
499128

499128

In [45]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]


In [46]:
a

[[1, 0], [0, 1]]

In [47]:
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [48]:
array = np.array ([1,2,3])

In [49]:
type(array)

numpy.ndarray

In [ ]:
a.dtype

dtype('float32')

In [ ]:
a

array([1., 2., 3.], dtype=float32)

In [ ]:
b = np.array ([1,2,3.567])

In [ ]:
b.dtype

dtype('float64')

In [ ]:
a = np.array([1,2,3], dtype=np.float32)  

In [ ]:
np.empty((1,3))

array([[1.19753282e-311, 0.00000000e+000, 4.94065646e-324]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

b = a.reshape(4,4)

In [ ]:
b = a.reshape(2,8)

In [ ]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
b[0:2,:]

#Rows, columns

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
b[2,1:]

array([10, 11, 12])

In [ ]:
b[:,::3]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12],
       [13, 16]])

In [ ]:
b[2:,3:]

array([[12],
       [16]])

In [ ]:
a.sum()

136

In [ ]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
b.sum(axis =0)

#Rows

array([28, 32, 36, 40])

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x * y


In [ ]:
a1 = np.linspace(10, 20, 5)

In [ ]:
a1

array([10. , 12.5, 15. , 17.5, 20. ])