#### 1. Import the numpy package under the name `np` (★☆☆)

#### 2. Print the numpy version

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
#Problem 4: Given a numpy array whose underlying data is of 'int32' type. Change the dtype of the given object to 'float64'.

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 4. Numpy where Problem

Say we have a numpy array A 

[[1 2 3]
 [4 5 6]]

Create a new matrix with Indices of elements <4

Output
Elements which are <4
array([1, 2, 3])

#### 5. Create a vector with values ranging from 10 to 49 (★☆☆)

#### 6. Reverse a vector (first element becomes last) (★☆☆)

#### 7. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

#### 8. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

#### 11. Create a 3x3 identity matrix (★☆☆)

#### 12. Create a 3x3x3 array with random values (★☆☆)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 4x4 matrix with values 0,1,2,3 just below the diagonal (★☆☆)

#### 19. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
---



#### 22. Normalize a 5x5 random matrix (★☆☆) Say X is 5*5 numpy array  Normalize i.e X - mean(X) / Standard Deviation of X [link text](https://)

#### 23. Numpy where Problem

Say we have a numpy array A 

[[1 2 3]
 [4 5 6]]

Create a new matrix with Indices of elements <4

Output
Elements which are <4
array([1, 2, 3])

#### 24. Do a dot product of 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Consider two random array A and B, check if they are equal (★★☆)

#### 26. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 27. Subtract the mean of each row of a matrix (★★☆):