### Numpy

In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3, 4, 5])

In [87]:
array1

array([2, 4, 6, 8])

In [3]:
array1

array([1, 2, 3, 4, 5])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(5,)

In [88]:
array1.ndim

1

In [89]:
array2 = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]])

In [90]:
array2.shape

(2, 5)

In [91]:
array2.ndim

2

In [92]:
array1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
array1
print(type(array1))
print(array1.shape)
print(array1.ndim)


<class 'numpy.ndarray'>
(2, 5)
2


In [ ]:
a = []

In [101]:
array2 = np.array([[1,2,3],[11,22, np.nan]], dtype = np.float32)


In [ ]:
aa

In [102]:
array2.dtype

dtype('float32')

In [103]:
array2

array([[ 1.,  2.,  3.],
       [11., 22., nan]], dtype=float32)

In [14]:
array_reshape = array2.reshape(3,2)

In [15]:
array_reshape

array([[ 1.,  2.],
       [ 3., 11.],
       [22., nan]])

In [16]:
array_reshape.shape

(3, 2)

In [17]:
array2 = np.array([[[[1,2,3,4,5],[4,5,6,7,8],[1.2,3.4,5.6,7.8,9.1],[4,4,4,4,5]]]])


In [18]:
array2 = np.array([[1,2,3,4,5],[4,5,6,7,8],[1.2,3.4,5.6,7.8,9.1],[4,4,4,4,5]])

In [19]:
array2.shape

(4, 5)

In [20]:
array2

array([[1. , 2. , 3. , 4. , 5. ],
       [4. , 5. , 6. , 7. , 8. ],
       [1.2, 3.4, 5.6, 7.8, 9.1],
       [4. , 4. , 4. , 4. , 5. ]])

In [21]:
np.shape

<function numpy.shape>

In [22]:
array2.shape

(4, 5)

In [23]:
array2.ndim

2

In [24]:
array2.shape?

In [25]:
array6 = np.array([[1,2,3.3],[4,5,6]])


In [26]:
array2 = np.array([[1,2,3,4,5],[4,5,6,7,8],[1.2,3.4,5.6,7.8,9.1],[4,4,4,4,5]], dtype = int)


In [26]:
#square matrix - Row and columns are equal

In [ ]:
#identify matrix - Prinipal Diagnal i 1 , other are zero
#ANYTHING WE multiply with identity matrix, returns the same value
#square matrix

In [107]:
array_ones = np.ones([3, 3], dtype=int)

In [108]:
array_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [109]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [110]:
array_Zero = np.zeros(8)

In [111]:
array_Zero

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [106]:
array_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Creating an array with existing data

In [31]:
x1 = ([3, 5], [5, 4], [6, 7])
a1 = np.asarray(x1, dtype=float)

In [32]:
np.array(x1)

array([[3, 5],
       [5, 4],
       [6, 7]])

In [33]:
type(x1)

tuple

In [34]:
a1

array([[3., 5.],
       [5., 4.],
       [6., 7.]])

### Array from numerical ranges


In [35]:
a1 = np.arange(0, 20, 3)

In [36]:
a1

array([ 0,  3,  6,  9, 12, 15, 18])

In [37]:
a1 = np.linspace(10, 20, 3)

In [38]:
a1

array([10., 15., 20.])

## Slicing

In [39]:
list1 = np.arange(10)
array1 = slice(2, 9, 3)
list1[array1]

array([2, 5, 8])

In [40]:
list1 = np.arange(10)
array1 = slice(2, 9)
list1[array1]

array([2, 3, 4, 5, 6, 7, 8])

In [41]:
list1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
list1 = np.arange(10)
array1 = list1[2: 9]
list1[array1]

array([2, 3, 4, 5, 6, 7, 8])

In [43]:
list1 = np.arange(10)
array1 = list1[2: 9: 2]
list1[array1]

array([2, 4, 6, 8])

In [44]:
len(list1)

10

In [45]:
array1

array([2, 4, 6, 8])

In [46]:
array1.shape

(4,)

In [47]:
array1.ndim

1

In [48]:
array7 = np.array([[[1,2,3,4,5],[4,5,6,7,8]],[[1,3,5,7,9],[4,4,4,4,5]]])
print(len(array7))
print(array7.ndim)

2
3


In [49]:
array7

array([[[1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8]],

       [[1, 3, 5, 7, 9],
        [4, 4, 4, 4, 5]]])

In [50]:
array7= np.array([[[1,3,4,5],[3,4,5,6]],[[5,4,5,6],[3,4,5,6]]])


In [51]:
array7.shape

(2, 2, 4)

In [52]:
array7.ndim

3

In [53]:
array7= np.array([[[1,3,4,5],[3,4,5,6],[3,4,5,6]],[[5,4,5,6],[3,4,5,6],[3,4,5,6]],[[5,4,5,6],[3,4,5,6],[3,4,5,6]],[[5,4,5,6],[3,4,5,6],[3,4,5,6]]])


In [54]:
print(array7.shape)
print(array7.ndim)

(4, 3, 4)
3


In [55]:
print(array7)

[[[1 3 4 5]
  [3 4 5 6]
  [3 4 5 6]]

 [[5 4 5 6]
  [3 4 5 6]
  [3 4 5 6]]

 [[5 4 5 6]
  [3 4 5 6]
  [3 4 5 6]]

 [[5 4 5 6]
  [3 4 5 6]
  [3 4 5 6]]]


### Integer indexing

In [56]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = a[[0, 1, 2], [0, 1, 0]]

In [57]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
print(b)

[1 4 5]


In [59]:
b = a[[0], [0]]

In [60]:
b

array([1])

In [61]:
a1 = np.array([[1,2,3, 5, np.nan, 9],[4, 5,6, 1,2,3],[7,8, 9, 5,6, 1],[10,np.nan,12, 9, 5,6]])
z = a1[1:4, 1:3]
z


array([[ 5.,  6.],
       [ 8.,  9.],
       [nan, 12.]])

In [62]:
a1

array([[ 1.,  2.,  3.,  5., nan,  9.],
       [ 4.,  5.,  6.,  1.,  2.,  3.],
       [ 7.,  8.,  9.,  5.,  6.,  1.],
       [10., nan, 12.,  9.,  5.,  6.]])

In [63]:
z = a1[1:, 1:]
z

array([[ 5.,  6.,  1.,  2.,  3.],
       [ 8.,  9.,  5.,  6.,  1.],
       [nan, 12.,  9.,  5.,  6.]])

In [64]:
a1

array([[ 1.,  2.,  3.,  5., nan,  9.],
       [ 4.,  5.,  6.,  1.,  2.,  3.],
       [ 7.,  8.,  9.,  5.,  6.,  1.],
       [10., nan, 12.,  9.,  5.,  6.]])

In [65]:
a1.shape

(4, 6)

In [66]:
z = a1[:4, :3]
z

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., nan, 12.]])

In [67]:
a1

array([[ 1.,  2.,  3.,  5., nan,  9.],
       [ 4.,  5.,  6.,  1.,  2.,  3.],
       [ 7.,  8.,  9.,  5.,  6.,  1.],
       [10., nan, 12.,  9.,  5.,  6.]])

In [68]:
y = a1[1:4, [1, 2, 3]]
y

array([[ 5.,  6.,  1.],
       [ 8.,  9.,  5.],
       [nan, 12.,  9.]])

In [69]:
a1[[1, 2, 3], [1, 2, 3]]

array([5., 9., 9.])

In [70]:
a1[1:3, 1:4]

array([[5., 6., 1.],
       [8., 9., 5.]])

In [71]:
a1

array([[ 1.,  2.,  3.,  5., nan,  9.],
       [ 4.,  5.,  6.,  1.,  2.,  3.],
       [ 7.,  8.,  9.,  5.,  6.,  1.],
       [10., nan, 12.,  9.,  5.,  6.]])

In [72]:
a1[a1<4]

array([1., 2., 3., 1., 2., 3., 1.])

In [73]:
arr1 = np.array([[ 8,  9,  6,  7,  8,  9,  6, 10, 11, 12,  9,  6], [ 8,  9,  6,  7,  8,  9,  6, 10, 11, 12,  9,  6]])

In [74]:
arr1.shape

(2, 12)

In [75]:
a = np.array([1, 5,  8, np.nan, 52, 65, np.nan])
a

array([ 1.,  5.,  8., nan, 52., 65., nan])

In [76]:
a[np.isnan(a)]

array([nan, nan])

In [77]:
a[~np.isnan(a)]

array([ 1.,  5.,  8., 52., 65.])

In [78]:
a1[np.isnan(a1)]

array([nan, nan])

In [79]:
a= np.array([[1,2,'dd'],[5,6,7],[1,2,3],[5,6,7]])
b= a[1:4,1:3]


In [80]:
b

array([['6', '7'],
       ['2', '3'],
       ['6', '7']], dtype='<U21')

In [81]:
b.dtype

dtype('<U21')

In [82]:
a

array([['1', '2', 'dd'],
       ['5', '6', '7'],
       ['1', '2', '3'],
       ['5', '6', '7']], dtype='<U21')

In [83]:
a= np.array([[1,2,1],[5,6,7],[1,2,3],[5,6,7]])
b= np.array([[1,2,1],[5,6,7],[1,2,3],[5,6,7]])


In [84]:
a

array([[1, 2, 1],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [85]:
b

array([[1, 2, 1],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [86]:
a+b

array([[ 2,  4,  2],
       [10, 12, 14],
       [ 2,  4,  6],
       [10, 12, 14]])